version: '3'

services:
  scraper-app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - MONGODB_RW_PASS=${MONGODB_RW_PASS}
      # For printing output
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/usr/src/app/